package jobs

import (
	"context"
	"fmt"
	"time"

	"github.com/iag/fleet-iot/iot"
	"github.com/iag/fleet-tool/backend/internal/models"
	"github.com/iag/fleet-tool/backend/internal/store"
)

// DetectTripsFromTelemetry creates auto_generated trips for all vehicles with pings in [from, to).
func DetectTripsFromTelemetry(ctx context.Context, iotStore *iot.Store, repo *store.Repository, from, to time.Time) (created int, err error) {
	if repo == nil || iotStore == nil {
		return 0, fmt.Errorf("store and repository required")
	}
	pairs, err := iotStore.DistinctVehicleDays(ctx, from, to)
	if err != nil {
		return 0, err
	}
	existing, err := repo.Trips.List(ctx)
	if err != nil {
		return 0, err
	}
	vehicles, err := repo.Vehicles.List(ctx)
	if err != nil {
		return 0, err
	}
	driverByVehicle := map[string]string{}
	for _, v := range vehicles {
		if v.DriverID != "" {
			driverByVehicle[v.ID] = v.DriverID
		}
	}

	for _, pair := range pairs {
		dayEnd := pair.Day.Add(24 * time.Hour)
		pings, err := iotStore.Track(ctx, pair.VehicleID, pair.Day, dayEnd, iot.MaxTrackRowLimit(), nil)
		if err != nil {
			return created, err
		}
		for _, d := range iot.DetectTripsFromPings(pair.VehicleID, pings) {
			if tripExistsJob(existing, pair.VehicleID, d.StartedAt) {
				continue
			}
			driverID := driverByVehicle[pair.VehicleID]
			if driverID == "" {
				driverID = "UNKNOWN"
			}
			trip := models.Trip{
				ID:            newTripID(pair.VehicleID, d.StartedAt),
				DriverID:      driverID,
				VehicleID:     pair.VehicleID,
				Date:          d.StartedAt.UTC().Format("2006-01-02"),
				StartLocation: d.StartLocation,
				EndLocation:   d.EndLocation,
				DistanceKm:    d.DistanceKm,
				DurationMin:   d.DurationMin,
				Status:        "completed",
				StartedAt:     d.StartedAt.UTC().Format(time.RFC3339),
				EndedAt:       d.EndedAt.UTC().Format(time.RFC3339),
				AutoGenerated: true,
				Notes:         "Detected from telemetry (fleet-jobs)",
			}
			saved, err := repo.Trips.Add(ctx, trip)
			if err != nil {
				return created, err
			}
			existing = append(existing, saved)
			created++
		}
	}
	return created, nil
}

func tripExistsJob(existing []models.Trip, vehicleID string, started time.Time) bool {
	for _, t := range existing {
		if t.VehicleID != vehicleID || !t.AutoGenerated || t.StartedAt == "" {
			continue
		}
		ts, err := time.Parse(time.RFC3339, t.StartedAt)
		if err != nil {
			continue
		}
		if ts.Equal(started) || ts.Sub(started).Abs() < time.Minute {
			return true
		}
	}
	return false
}

func newTripID(vehicleID string, started time.Time) string {
	return fmt.Sprintf("TRP-TEL-%s-%d", vehicleID, started.Unix())
}
