package jobs

import (
	"strings"
	"testing"
	"time"

	fuelpkg "github.com/iag/fleet-tool/backend/internal/fuel"
	"github.com/iag/fleet-tool/backend/internal/models"
)

// These cover the decision logic the scheduled jobs run unattended. Their
// failure mode isn't a crash — it's a plausible wrong answer (a duplicated
// trip, a silently widened aggregation window, an anomaly matched to the wrong
// refuel) that nobody is watching for.

func autoTrip(vehicleID, startedAt string) models.Trip {
	return models.Trip{VehicleID: vehicleID, StartedAt: startedAt, AutoGenerated: true}
}

func TestTripExistsJob(t *testing.T) {
	started := time.Date(2026, 3, 4, 8, 30, 0, 0, time.UTC)

	cases := []struct {
		name     string
		existing []models.Trip
		want     bool
	}{
		{"exact timestamp", []models.Trip{autoTrip("V1", "2026-03-04T08:30:00Z")}, true},
		{"within the one-minute window", []models.Trip{autoTrip("V1", "2026-03-04T08:30:59Z")}, true},
		{"earlier, still within window", []models.Trip{autoTrip("V1", "2026-03-04T08:29:01Z")}, true},
		// The guard is `< time.Minute`, so a full minute apart is a new trip.
		{"exactly one minute apart", []models.Trip{autoTrip("V1", "2026-03-04T08:31:00Z")}, false},
		{"different vehicle", []models.Trip{autoTrip("V2", "2026-03-04T08:30:00Z")}, false},
		{"manually created trip does not suppress", []models.Trip{{VehicleID: "V1", StartedAt: "2026-03-04T08:30:00Z"}}, false},
		{"missing StartedAt", []models.Trip{autoTrip("V1", "")}, false},
		{"unparseable StartedAt is skipped", []models.Trip{autoTrip("V1", "not-a-timestamp")}, false},
		{"no candidates", nil, false},
		{"matches on the second candidate", []models.Trip{autoTrip("V9", "2026-03-04T08:30:00Z"), autoTrip("V1", "2026-03-04T08:30:00Z")}, true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := tripExistsJob(tc.existing, "V1", started); got != tc.want {
				t.Fatalf("tripExistsJob() = %v, want %v", got, tc.want)
			}
		})
	}
}

// A non-UTC start must not produce a different ID than the same instant in UTC:
// the ID keys on Unix seconds, and re-running the job from a differently-zoned
// caller would otherwise duplicate every trip.
func TestNewTripID_stableAcrossZones(t *testing.T) {
	utc := time.Date(2026, 3, 4, 8, 30, 0, 0, time.UTC)
	east := utc.In(time.FixedZone("UTC+3", 3*60*60))

	if got, want := newTripID("V1", east), newTripID("V1", utc); got != want {
		t.Fatalf("zone changed the ID: %q vs %q", got, want)
	}
	if want := "TRP-TEL-V1-"; !strings.HasPrefix(newTripID("V1", utc), want) {
		t.Fatalf("newTripID() = %q, want prefix %q", newTripID("V1", utc), want)
	}
}

func TestResolveAggregateRange_defaultsToYesterday(t *testing.T) {
	from, to, err := ResolveAggregateRange("", "")
	if err != nil {
		t.Fatalf("ResolveAggregateRange: %v", err)
	}
	if got := to.Sub(from); got != 24*time.Hour {
		t.Fatalf("default window = %v, want 24h", got)
	}
	if !from.Equal(from.Truncate(24 * time.Hour)) {
		t.Fatalf("from = %v, want a midnight boundary", from)
	}
	if !from.Before(time.Now().UTC()) {
		t.Fatalf("from = %v, want a past day", from)
	}
}

func TestResolveAggregateRange(t *testing.T) {
	day := func(s string) time.Time {
		t.Helper()
		v, err := time.ParseInLocation(DayLayout, s, time.UTC)
		if err != nil {
			t.Fatalf("parse %q: %v", s, err)
		}
		return v
	}

	t.Run("from only spans that single day", func(t *testing.T) {
		from, to, err := ResolveAggregateRange("2026-03-04", "")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !from.Equal(day("2026-03-04")) || !to.Equal(day("2026-03-05")) {
			t.Fatalf("got %v..%v, want 2026-03-04..2026-03-05", from, to)
		}
	})

	// --to names a day that should be included, so the exclusive end is the
	// following midnight. An off-by-one here silently drops the last day.
	t.Run("to is inclusive", func(t *testing.T) {
		from, to, err := ResolveAggregateRange("2026-03-04", "2026-03-06")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !from.Equal(day("2026-03-04")) || !to.Equal(day("2026-03-07")) {
			t.Fatalf("got %v..%v, want 2026-03-04..2026-03-07", from, to)
		}
	})

	t.Run("same day is a valid one-day range", func(t *testing.T) {
		from, to, err := ResolveAggregateRange("2026-03-04", "2026-03-04")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := to.Sub(from); got != 24*time.Hour {
			t.Fatalf("window = %v, want 24h", got)
		}
	})

	t.Run("exactly ninety days is allowed", func(t *testing.T) {
		if _, _, err := ResolveAggregateRange("2026-01-01", "2026-03-31"); err != nil {
			t.Fatalf("90-day range rejected: %v", err)
		}
	})

	for _, tc := range []struct {
		name, from, to, wantErr string
	}{
		{"to before from", "2026-03-06", "2026-03-04", "on/after"},
		{"over the ninety-day cap", "2026-01-01", "2026-04-30", "90 days"},
		{"malformed from", "04/03/2026", "", "--from"},
		{"malformed to", "2026-03-04", "not-a-day", "--to"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := ResolveAggregateRange(tc.from, tc.to)
			if err == nil {
				t.Fatalf("expected an error containing %q", tc.wantErr)
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("error = %q, want it to mention %q", err, tc.wantErr)
			}
		})
	}
}

func TestNearestDropHint(t *testing.T) {
	hint := func(day string, id int64) *fuelpkg.TelemetryDropHint {
		t.Helper()
		ts, err := time.Parse(DayLayout, day)
		if err != nil {
			t.Fatalf("parse %q: %v", day, err)
		}
		return &fuelpkg.TelemetryDropHint{EventID: id, TS: ts}
	}

	t.Run("picks the closest hint, not the first", func(t *testing.T) {
		hints := []*fuelpkg.TelemetryDropHint{
			hint("2026-03-01", 1), // 5 days out
			hint("2026-03-05", 2), // 1 day out — closest
			hint("2026-03-09", 3), // 3 days out
		}
		got, ok := nearestDropHint(hints, "2026-03-06")
		if !ok {
			t.Fatal("expected a match")
		}
		if got.EventID != 2 {
			t.Fatalf("matched event %d, want 2 (the nearest)", got.EventID)
		}
	})

	t.Run("a hint before the record still matches", func(t *testing.T) {
		got, ok := nearestDropHint([]*fuelpkg.TelemetryDropHint{hint("2026-03-01", 7)}, "2026-03-04")
		if !ok || got.EventID != 7 {
			t.Fatalf("got %v/%v, want event 7 matched", got, ok)
		}
	})

	// The window is 7 days either side; 8 days out must not be attributed.
	t.Run("outside the window", func(t *testing.T) {
		if _, ok := nearestDropHint([]*fuelpkg.TelemetryDropHint{hint("2026-03-01", 1)}, "2026-03-09"); ok {
			t.Fatal("hint 8 days away should not match")
		}
	})

	t.Run("exactly at the window edge", func(t *testing.T) {
		if _, ok := nearestDropHint([]*fuelpkg.TelemetryDropHint{hint("2026-03-01", 1)}, "2026-03-08"); !ok {
			t.Fatal("hint exactly 7 days away should match")
		}
	})

	for _, tc := range []struct {
		name       string
		hints      []*fuelpkg.TelemetryDropHint
		recordDate string
	}{
		{"no hints", nil, "2026-03-04"},
		{"no record date", []*fuelpkg.TelemetryDropHint{hint("2026-03-04", 1)}, ""},
		{"unparseable record date", []*fuelpkg.TelemetryDropHint{hint("2026-03-04", 1)}, "04/03/2026"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got, ok := nearestDropHint(tc.hints, tc.recordDate); ok || got != nil {
				t.Fatalf("got %v/%v, want no match", got, ok)
			}
		})
	}
}

func TestAnomalyTypesEqual(t *testing.T) {
	cases := []struct {
		name string
		a, b models.AnomalyTypes
		want bool
	}{
		{"identical", models.AnomalyTypes{"drop", "spike"}, models.AnomalyTypes{"drop", "spike"}, true},
		{"both empty", models.AnomalyTypes{}, models.AnomalyTypes{}, true},
		{"nil and empty", nil, models.AnomalyTypes{}, true},
		{"different length", models.AnomalyTypes{"drop"}, models.AnomalyTypes{"drop", "spike"}, false},
		// Order-sensitive: callers must sort before comparing, or an unchanged
		// anomaly set reads as changed and rewrites history on every pass.
		{"same members, different order", models.AnomalyTypes{"spike", "drop"}, models.AnomalyTypes{"drop", "spike"}, false},
		{"different members", models.AnomalyTypes{"drop"}, models.AnomalyTypes{"spike"}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := anomalyTypesEqual(tc.a, tc.b); got != tc.want {
				t.Fatalf("anomalyTypesEqual(%v, %v) = %v, want %v", tc.a, tc.b, got, tc.want)
			}
		})
	}
}

func TestContainsType(t *testing.T) {
	types := models.AnomalyTypes{"drop", "spike"}
	if !containsType(types, "spike") {
		t.Fatal("expected spike to be found")
	}
	if containsType(types, "siphon") {
		t.Fatal("siphon is not present")
	}
	if containsType(nil, "drop") {
		t.Fatal("nil set contains nothing")
	}
	if containsType(types, "Spike") {
		t.Fatal("matching should be case-sensitive")
	}
}

func TestHistoryNoteContains(t *testing.T) {
	h := models.AnomalyHistory{
		{At: "2026-03-01T00:00:00Z", Event: "flagged", Note: "auto: telemetry drop matched"},
		{At: "2026-03-02T00:00:00Z", Event: "investigated"},
	}
	if !historyNoteContains(h, "telemetry drop") {
		t.Fatal("expected substring match in note")
	}
	if historyNoteContains(h, "siphon") {
		t.Fatal("unexpected match")
	}
	if historyNoteContains(nil, "anything") {
		t.Fatal("empty history matches nothing")
	}
	// Events carrying no note must not be treated as matching the empty string
	// in a way that surprises callers — an empty marker matches any event.
	if !historyNoteContains(h, "") {
		t.Fatal("empty marker is a substring of every note")
	}
}
